### ISSUE TITLE
Update contact details and license file

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/SDC-BIDS-sMRI#59]
Hi folks, we received an email to The Carpentries account requesting permission to re-use one of the images from this lesson in a publication, and asking for a copy of that image at higher resolution.

We received that email because the contact email address on the lesson site is still set to team@carpentries.org. Please could you update it to an address where interested people can reach the authors?

Regarding the permission request: I informed the requester that the CC-BY license of the lesson granted them permission as long as they cited the source of the material. However, [the license file for the lesson](https://github.com/carpentries-incubator/SDC-BIDS-sMRI/blob/gh-pages/LICENSE.md) talks about citing it as copyright of Software Carpentry (this is a problem across most lessons in the Incubator, related to how we create the lesson repositories from a template). I advised them to cite it differently, but you may like to update your LICENSE.md to contain information specific to this lesson.

Finally, I could not help with providing a copy of the image in higher resolution, and have suggested that they open an issue here to request it.

**Comment by nikhil153** [comment]
Hi @tobyhodges - I have updated the email in the [_config.yml](https://github.com/carpentries-incubator/SDC-BIDS-sMRI/blob/gh-pages/_config.yml#L33). Let me know if it needs to be added anywhere else. 

The figure they are interested in is generate by this [notebook](https://github.com/carpentries-incubator/SDC-BIDS-sMRI/blob/gh-pages/code/1_sMRI_modalities.ipynb). They should be able to regenerate and save a high-res copy from there. If not I can send them via email as well.

**Comment by tobyhodges** [comment]
Changing the email address in `config.yml` should be sufficient. Thanks @nikhil153!

I will send the notebook to them, and let them know that you've updated the contact email address. They will be able to contact you directly now if needed 👍
